### ISSUE TITLE
加载静态资源报错

### ISSUE THREAD

**Issue by lizhongkun** [hellojayjay/qiankun-ng9#1]
在子应用中引用了本地静态资源，在主应用中，子应用访问的资源就请求不到了
![image](https://user-images.githubusercontent.com/41602501/91560644-bfb0db80-e96c-11ea-8d0b-8f2bc03e62c2.png)
![image](https://user-images.githubusercontent.com/41602501/91560744-e8d16c00-e96c-11ea-9205-0457b68b1d17.png)

**Comment by hellojayjay** [comment]
> 在子应用中引用了本地静态资源，在主应用中，子应用访问的资源就请求不到了
> ![image](https://user-images.githubusercontent.com/41602501/91560644-bfb0db80-e96c-11ea-8d0b-8f2bc03e62c2.png)
> ![image](https://user-images.githubusercontent.com/41602501/91560744-e8d16c00-e96c-11ea-9205-0457b68b1d17.png)

最新的代码已经解决，改动见：[a6929dd](https://github.com/hellojayjay/qiankun-ng9/commit/d3b03f30dc968cf78ccc79a1a8b4359f9e22cff0)

思路：在localhost:7103/assets/test.png是可以访问的，而主应用中是localhost:4200，所以可以在主应用中配置代理，同时需要更改子应用的静态资源路径为带有代理标识符的路径，如`/angular9/aseets/xxx.jpg`
